### PR TITLE
Only lex addresses when necessary

### PR DESCRIPTION
**Pull request by mpeterv**
Hello! This PR improves error handling in parser and fixes some minor bugs. The problem was that `lexer.next()` could always return a table (an IPv4/IPv6/MAC address), although addresses are only valid as arguments after certain primitives. Parsing functions generally do not expect tables and either crash or show strange errors on them (e.g. `bad token table 0xabcdef`).

The main change is to only lex addesses when an option `address` is set, similarly to `maybe_arithmetic` for arithmetic expressions. As a result, there is no number/address ambiguity, and code can be simplified. For instance, two functions for IPv4 parsing can be merged: if `address` option is set, a bare number can always be interpreted as a single-field IPv4 address.

Follow-up commits improve various error messages and improve compatibility with tcpdump (where it makes sense): octal literals are now valid not only in arithmetic expressions but also as arguments, while hexadecimal literals are disallowed in port ranges (e.g. `0x1-0x2` should be rejected).

The last commit fixes a bug which existed before, but only started triggering in one of doc examples with the previous commits of this PR: caching token in `lexer.peek` is unsafe if it is cached and consumed with different options. E.g. in `(len-4>10)` logical expression parser peeks `len-4` without `maybe_arithmetic` option, and then primitive parser tries to consume it and throws `len-4 is not a recognized keyword...` error.

### CODE REVIEW

**Comment by kbara** [comment]
Thank you! It looks good to me, and I've asked my colleagues who have hacked on the parser if they want to take a look as well.

**Comment by kbara** [comment]
I've added more testing, generating well-formed Ethernet addresses and IPv6 addresses (bare and with netmasks). The pflang expressions generated on https://github.com/Igalia/pflua/pull/219 pass flawlessly when on a branch based on mpeterv's work, and fail miserably on current master.

**Comment by andywingo** [comment]
First off: awesome work, thank you!  Secondly, my apologies I asked @kbara to hold off on merging this because I wanted to look at it, and it took me a long time to get to it.  My bad.

I think one of the reasons to be honest is because the patchset is a bit large to review.  I think in the future it might make it easier if the patches were submitted separately.  Also it would be good if each patch does not regress -- for example now taking a look at https://github.com/mpeterv/pflua/commit/3375a413d025b1970adb7bb7034df73f94aa1c6e I didn't realize that the bug that it introduces was fixed by https://github.com/mpeterv/pflua/commit/1394b279480f507489df0d081aa28ea7fc7793ee; best to squash these together :)  Smaller patches makes feedback easier too because we can fix up earlier patches in isolation.  Dunno.  Really great work though, I'll handle the merges.

**Comment by andywingo** [comment]
I've merged the first two commits.  Thanks!

**Comment by andywingo** [comment]
Er, rather I merged the first and the last commit.

**Comment by mpeterv** [comment]
@andywingo the idea was that the first commit on its own looks like refactoring and may not justify itself, but all others depend on it. I agree with you on all points though. Do you want me to rebase and send pull requests for other commits?

**Comment by andywingo** [comment]
@mpeterv Yes please rebase + separate PRs would be really great :-)  Thank you!

**Comment by dpino** [comment]
Closing PR as it was split in several PR and all changes have been merged.

**Pull request closed without merging**
