### PR TITLE
Generate 'ether' clauses, and IPv6 addresses and netmasks.

### PR DESCRIPTION
**Pull request by kbara**

### CODE REVIEW

**Comment by kbara** [comment]
This relies on https://github.com/Igalia/pflua/pull/213 or equivalent work being merged.

**Comment by kbara** [comment]
An example of a filter which works after rebasing on #213 , but not on master:
```not not not dst net 76.75.61.0/26 or net 205 && sctp and icmp6```

**Comment by kbara** [comment]
Tested against 1f446ac6; enough equivalent work has been merged that this now passes, so can be merged after review.

**Comment by dpino** [comment]
LGTM.

**Comment by kbara** [comment]
Merging despite test failure; it's an artefact of the version of master that this was based on, and does not appear when this is merged onto current master.

**Pull request merged**
