### PR TITLE
Replace constant numbers for constant literals

### PR DESCRIPTION
**Pull request by dpino**
This fixes issue #158 .

### CODE REVIEW

**Comment by kbara** [comment]
Thank you!

Bikesheds:
could you call PAYLOAD something more descriptive, (maybe ETHER_PAYLOAD, though it's not fantastic)?

Would you give names to more of the literals, like 1500, 40, 224, 2863268608, etc?

**Comment by dpino** [comment]
I replaced other constant numbers for literals. I did it to the extent I could, there are protocols I could not find information about what the numbers meant, like in DECNET and a few others. In addition, I had to declare some variables within the scope they were used (within a function mostly) since it seems is not possible to declare more than 200 variables in a Lua module (it's a language constraint).

**Comment by kbara** [comment]
Thank you! This files looks a lot better than when you started. :)
And having variables be as local as possible is a good thing; it makes the code more readable.

Minor nits: can you easily add names to the numbers in any of the following?
* ```{ '=', { '[ip6]', 40, 1 }, proto } } } }```
* ```{ '=', { '[ip6]', IPV6_NEXT_HEADER, 1 }, 44 }```
* ```return { '=', { '[ip]', ETHER_PAYLOAD + 2, 1 }, 224 }```
* ```return { '=', { '[ip6]', ETHER_PAYLOAD + 10, 1 }, 255 }``` (both the 10 and the 255)
* the 14s in expand_offset
* expand_decnet_* (don't worry too much about this one).

**Comment by kbara** [comment]
LGTM. Thank you very much! I know this kind of patch is tedious to write, but it makes code better over the long run. :)

**Pull request merged**
